<?php
echo "<center>";
echo "<table id='user' border='1'>";
	echo "<tr >";
		echo "<td class='centerText'></td>";
		echo "<td class='centerText'>";
			echo "<center>";
			echo "<table border='1'>";
			echo "<tr>";
			echo "<td id='".$_SESSION['user1']."' class='centerText'></td>";
			echo "</tr>";
			echo "<tr>";
			echo "<td id='u1' class='centerText'>".ucfirst($_SESSION['user1'])."</td>";
			echo "</tr>";
			echo "<tr>";
			echo "<td id='u10' class='centerText'><img src='".SITE_URL."/images/greenarrowup.gif' height=50 width=50/></td>";
			echo "</tr>";
			echo "<tr>";
			echo "<td id='popmessage' class='centerText'></td>";
			echo "</tr>";
			echo "</table>";
			echo "</center>";
		echo "</td>";
		echo "<td class='centerText'></td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td class='centerText'>";
		echo "<center>";
		echo "<table>";
			echo "<tr>";
			echo "<td id='".$_SESSION['user2']."' class='centerText' colspan=2></td>";
			echo "</tr>";
			echo "<tr>";
			echo "<td id='u2' class='centerText'>".ucfirst($_SESSION['user2']);
			echo "<td id='u21' class='centerText'><img src='".SITE_URL."/images/greenarrowleft.gif' height=50 width=50/></td>";
			echo "</tr>";
			echo "</table>";
		echo "<center>";
		echo "</td>";
		echo "<td  class='centerText' id='slips'>";
			echo "<center>";
			echo "<table border='1'>";
				echo "<tr>";
					echo "<td class ='rotateimage0 centerText'><img src='".SITE_URL."/images/rolledpaper1.png' height=50 width=50/> </td>";
					echo "<td class ='rotateimage1 centerText'><img src='".SITE_URL."/images/rolledpaper2.png' height=50 width=50/> </td>";
				echo "</tr>";
				echo "<tr>";
					echo "<td class ='rotateimage2 centerText'><img src='".SITE_URL."/images/rolledpaper3.png' height=50 width=50/> </td>";
					echo "<td class ='rotateimage3 centerText'><img src='".SITE_URL."/images/rolledpaper4.png' height=50 width=50/> </td>";
				echo "</tr>";
				echo "<tr>";
					echo "<td  class='centerText' colspan=2></td>";
					
				echo "</tr>";
			echo "</table>";
			echo "</center>";
		echo "</td class='centerText'>";
			echo "<td class='centerText'>";
			echo "<center>";
			echo "<table>";
			echo "<tr>";
			echo "<td id='".$_SESSION['user4']."' class='centerText' colspan=2></td>";
			echo "</tr>";
			echo "<tr>";
			echo "<td id='u43' class='centerText'><img src='".SITE_URL."/images/greenarrowright.gif' height=50 width=50/></td>";
			echo "<td id='u4' class='centerText'>".ucfirst($_SESSION['user4']);
			echo "</tr>";
			echo "</table>";
			echo "</center>";
		echo "</td class='centerText'>";
	echo "</tr>";
	echo "<tr>";
		echo "<td class='centerText'></td>";
		echo "<td class='centerText'>";
			echo "<center>";
			echo "<table>";
			echo "<tr>";
			echo "<td id='".$_SESSION['user3']."' class='centerText'></td>";
			echo "</tr>";
			echo "<tr>";
			echo "<td id='u32' class='centerText'><img src='".SITE_URL."/images/greenarrowdown.gif' height=50 width=50/></td>";
			echo "</tr>";
			echo "<tr>";
			echo "<td id='u3' class='centerText'>".ucfirst($_SESSION['user3']);
			echo "</tr>";
			echo "</table>";
			echo "</center>";
		echo "</td>";
		echo "<td class='centerText'></td>";
	echo "</tr>";
echo "</table>";
echo "</center>";
	
?>
<style>
.centerText{
   text-align: center;
}
</style>
